# Generated by Django 4.1.10 on 2023-09-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='User',
            field=models.CharField(default='', max_length=100),
        ),
    ]
