# Generated by Django 4.1.10 on 2023-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_details_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
